# This is the muckebox server configuration file
#
# Do not edit this file directly, but copy it somewhere, modify to your
# liking (especially the password field), then use the -c parameter
# to load it.
#
# The default search path is
#
#   /etc/muckebox/config.py
#   ~/.config/muckebox/config.py
#
# If you put the file in one of those pathes, you don't need to use -c.
#
# Note that this file is just a Python module, you can do whatever you want,
# as long as it exports the config dict below filled with appropriate values.

# Root directory for run-time data (this is just used as an alias below)
data_path = '/var/muckebox'

config = {
    # Where you store your music
    'library_path' :            data_path + '/Music',

    # File where we store our database
    'db_path' :                 data_path + '/muckebox.db',

    # A directory where we store cached transcodings
    'cache_path' :              data_path + '/cache',

    # Where to store our log files
    'log_path' :                data_path + '/log',

    # Filenames for SSL, SSL will be disabled if those cannot be found
    #
    # Those pathes can be relative to the directory containing the
    # config file
    'ssl_key_path' :            'ssl/server.key',
    'ssl_certificate_path' :    'ssl/server.crt',

    # HTTP authentification password the clients must use
    'password' :                '',

    ### The following settings are optional and can be omitted in your
    ### config file

    # TCP port to listen on
    'port' :                    2342,

    # Name of the album artist for various artists albums (i.e. albums with
    # different artist tags
    'va_artist' :               'VA',

    # Unless this is set to True, the server will not start without
    # SSL keys and a password
    'allow_insecure':           False,

    # Maximum size of the cache in bytes (you can use a suffix like 'M',
    # 'G' etc. to abbreviate)
    'maximum_cache_size' :      '10G'
}
